{"timestamp":"2018-09-29T15:53:24.583Z", "level":"error", "message":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]", "stack":"Error: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]    at process.on (G:\Root\Blockchain\Citex\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-01T06:07:16.606Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-01T08:47:43.973Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-01T08:48:58.142Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:44:43.664Z", "level":"error", "message":"listen EADDRINUSE :::3000", "stack":"Error: listen EADDRINUSE :::3000    at Object._errnoException (util.js:1022:11)    at _exceptionWithHostPort (util.js:1044:20)    at Server.setupListenHandle [as _listen2] (net.js:1367:14)    at listenInCluster (net.js:1408:12)    at Server.listen (net.js:1492:7)    at Function.listen (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\node_modules\express\lib\application.js:618:24)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:15:5)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-08T12:44:46.724Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:45:20.302Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:46:10.533Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:46:23.292Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:46:27.886Z", "level":"error", "message":"ReferenceError: JS is not defined", "stack":"Error: ReferenceError: JS is not defined    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-08T12:46:32.756Z", "level":"error", "message":"ValidationError: type: Path `type` is required.", "stack":"Error: ValidationError: type: Path `type` is required.    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-08T12:49:31.682Z", "level":"error", "message":"Error: connection not open", "stack":"Error: Error: connection not open    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-08T15:13:09.102Z", "level":"error", "message":"Unexpected token )", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:64        })         ^SyntaxError: Unexpected token )    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\events.js:1:84)"}
{"timestamp":"2018-10-08T15:20:45.040Z", "level":"error", "message":"std is not defined", "stack":"ReferenceError: std is not defined    at G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:10:15    at ChildProcess.exithandler (child_process.js:267:7)    at emitTwo (events.js:126:13)    at ChildProcess.emit (events.js:214:7)    at maybeClose (internal/child_process.js:925:16)    at Socket.stream.socket.on (internal/child_process.js:346:11)    at emitOne (events.js:116:13)    at Socket.emit (events.js:211:7)    at Pipe._handle.close [as _onclose] (net.js:567:12)"}
{"timestamp":"2018-10-08T15:24:05.217Z", "level":"error", "message":"missing path", "stack":"AssertionError [ERR_ASSERTION]: missing path    at Module.require (module.js:594:3)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-08T15:24:08.347Z", "level":"error", "message":"Cannot find module './startup/'", "stack":"Error: Cannot find module './startup/'    at Function.Module._resolveFilename (module.js:547:15)    at Function.Module._load (module.js:474:25)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-08T15:24:14.063Z", "level":"error", "message":"Cannot read property 'set' of undefined", "stack":"TypeError: Cannot read property 'set' of undefined    at module.exports (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\server.js:4:9)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:28)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-08T15:24:30.148Z", "level":"error", "message":"Cannot read property 'set' of undefined", "stack":"TypeError: Cannot read property 'set' of undefined    at module.exports (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\server.js:4:9)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:41)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-08T15:24:31.037Z", "level":"error", "message":"Error: connection not open", "stack":"Error: Error: connection not open    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-08T15:24:53.967Z", "level":"error", "message":"Cannot read property 'set' of undefined", "stack":"TypeError: Cannot read property 'set' of undefined    at module.exports (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\server.js:4:9)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:41)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-09T09:01:51.146Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":"Error: listen EADDRINUSE 0.0.0.0:3000    at Object._errnoException (util.js:1022:11)    at _exceptionWithHostPort (util.js:1044:20)    at Server.setupListenHandle [as _listen2] (net.js:1367:14)    at listenInCluster (net.js:1408:12)    at doListen (net.js:1517:7)    at _combinedTickCallback (internal/process/next_tick.js:141:11)    at process._tickCallback (internal/process/next_tick.js:180:9)    at Function.Module.runMain (module.js:695:11)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-13T06:59:18.315Z", "level":"error", "message":"require(...).syncPastEvents is not a function", "stack":"TypeError: require(...).syncPastEvents is not a function    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:10:29)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-13T07:01:14.957Z", "level":"error", "message":"Cannot find module './events/events'", "stack":"Error: Cannot find module './events/events'    at Function.Module._resolveFilename (module.js:547:15)    at Function.Module._load (module.js:474:25)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-13T07:01:22.382Z", "level":"error", "message":"Cannot read property 'use' of undefined", "stack":"TypeError: Cannot read property 'use' of undefined    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:15:4)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-13T07:02:57.704Z", "level":"error", "message":"StatusCodeError: 403 - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n<title>403 - Forbidden: Access is denied.</title>\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\n</head>\n<body>\n<div id=\"header\"><h1>Server Error</h1></div>\n<div id=\"content\">\n<div class=\"content-container\"><fieldset>\n<h2>403 - Forbidden: Access is denied.</h2>\n<h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>\n</fieldset></div>\n</div>\n</body>\n</html>\n"", "stack":"Error: StatusCodeError: 403 - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n<title>403 - Forbidden: Access is denied.</title>\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\n</head>\n<body>\n<div id=\"header\"><h1>Server Error</h1></div>\n<div id=\"content\">\n<div class=\"content-container\"><fieldset>\n<h2>403 - Forbidden: Access is denied.</h2>\n<h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>\n</fieldset></div>\n</div>\n</body>\n</html>\n"    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-13T07:27:50.806Z", "level":"error", "message":"Error: connection not open", "stack":"Error: Error: connection not open    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-13T07:28:52.127Z", "level":"error", "message":"Error: connection not open", "stack":"Error: Error: connection not open    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-13T07:29:37.845Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":"Error: listen EADDRINUSE 0.0.0.0:3000    at Object._errnoException (util.js:1022:11)    at _exceptionWithHostPort (util.js:1044:20)    at Server.setupListenHandle [as _listen2] (net.js:1367:14)    at listenInCluster (net.js:1408:12)    at doListen (net.js:1517:7)    at _combinedTickCallback (internal/process/next_tick.js:141:11)    at process._tickCallback (internal/process/next_tick.js:180:9)    at Function.Module.runMain (module.js:695:11)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-13T07:51:48.367Z", "level":"error", "message":"Unexpected identifier", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:72                    cawait insertEvent(event)                           ^^^^^^^^^^^SyntaxError: Unexpected identifier    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:51:52.864Z", "level":"error", "message":"Unexpected reserved word", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:72                    const await insertEvent(event)                          ^^^^^SyntaxError: Unexpected reserved word    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:51:54.492Z", "level":"error", "message":"Missing initializer in const declaration", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:72                    const evawait insertEvent(event)                          ^^^^^^^SyntaxError: Missing initializer in const declaration    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:52:19.275Z", "level":"error", "message":"Unexpected token )", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:73                    console.log(e.)                                  ^SyntaxError: Unexpected token )    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:52:40.697Z", "level":"error", "message":"Error: connection not open", "stack":"Error: Error: connection not open    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-13T07:53:10.438Z", "level":"error", "message":"TypeError: Cannot read property '_id' of undefined", "stack":"Error: TypeError: Cannot read property '_id' of undefined    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-13T07:53:45.634Z", "level":"error", "message":"Unexpected reserved word", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:28  const await token.save();        ^^^^^SyntaxError: Unexpected reserved word    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:53:50.176Z", "level":"error", "message":"Missing initializer in const declaration", "stack":"G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\events\token.js:28  const eventawait token.save();        ^^^^^^^^^^SyntaxError: Missing initializer in const declaration    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:13:1)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)"}
{"timestamp":"2018-10-13T07:54:24.763Z", "level":"error", "message":"SyntaxError: Identifier 'event' has already been declared", "stack":"Error: SyntaxError: Identifier 'event' has already been declared    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-13T07:56:51.885Z", "level":"error", "message":"ReferenceError: eventsIds is not defined", "stack":"Error: ReferenceError: eventsIds is not defined    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"timestamp":"2018-10-13T08:04:09.738Z", "level":"error", "message":"e is not defined", "stack":"ReferenceError: e is not defined    at Object.<anonymous> (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\server.js:14:13)    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Function.Module.runMain (module.js:693:10)    at startup (bootstrap_node.js:188:16)    at bootstrap_node.js:609:3"}
{"timestamp":"2018-10-14T14:06:59.814Z", "level":"error", "message":"TypeError: Cannot read property 'replace' of undefined", "stack":"Error: TypeError: Cannot read property 'replace' of undefined    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-14T14:07:32.964Z", "level":"error", "message":"TypeError: Cannot read property 'replace' of undefined", "stack":"Error: TypeError: Cannot read property 'replace' of undefined    at process.on (G:\Root\Blockchain\areaTeck\citexToken\citex-ui\server\startup\logging.js:44:15)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)    at runMicrotasksCallback (internal/process/next_tick.js:124:9)    at _combinedTickCallback (internal/process/next_tick.js:131:7)    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"timestamp":"2018-10-14T14:10:46.266Z", "level":"error", "message":"Unexpected token function", "stack":""}
{"timestamp":"2018-10-14T14:10:56.300Z", "level":"error", "message":"Unexpected token async", "stack":""}
{"timestamp":"2018-10-14T14:11:00.192Z", "level":"error", "message":"Unexpected token async", "stack":""}
{"timestamp":"2018-10-14T14:11:01.469Z", "level":"error", "message":"Unexpected token async", "stack":""}
{"timestamp":"2018-10-14T14:11:19.947Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:11:19.950Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:11:37.265Z", "level":"error", "message":"Unexpected token }", "stack":""}
{"timestamp":"2018-10-14T14:13:59.287Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:13:59.288Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:14:45.569Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:14:45.572Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:18:50.662Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":""}
{"timestamp":"2018-10-14T14:19:02.890Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:19:02.892Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:20:26.351Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":""}
{"timestamp":"2018-10-14T14:21:13.284Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:21:13.285Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:21:37.134Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":""}
{"timestamp":"2018-10-14T14:21:40.261Z", "level":"error", "message":"listen EADDRINUSE 0.0.0.0:3000", "stack":""}
{"timestamp":"2018-10-14T14:21:52.546Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:21:52.548Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:21:53.045Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:21:53.047Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:22:29.411Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:26:22.175Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:26:22.177Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-14T14:28:57.912Z", "level":"error", "message":"Web3.providers.HttptProvider is not a constructor", "stack":""}
{"timestamp":"2018-10-14T14:29:52.330Z", "level":"error", "message":"Error: Invalid JSON RPC response: """, "stack":""}
{"timestamp":"2018-10-14T14:30:54.923Z", "level":"error", "message":"Error: CONNECTION ERROR: Couldn't connect to node ws://ropsten.infura.io/ws.", "stack":""}
{"timestamp":"2018-10-14T14:31:00.204Z", "level":"error", "message":"Web3.providers.WProvider is not a constructor", "stack":""}
{"timestamp":"2018-10-14T14:31:01.913Z", "level":"error", "message":"Web3.providers.WProvider is not a constructor", "stack":""}
{"timestamp":"2018-10-14T14:31:04.469Z", "level":"error", "message":"Web3.providers.WebsocProvider is not a constructor", "stack":""}
{"timestamp":"2018-10-14T14:35:33.775Z", "level":"error", "message":"web3 is not defined", "stack":""}
{"timestamp":"2018-10-14T14:35:40.889Z", "level":"error", "message":"web is not defined", "stack":""}
{"timestamp":"2018-10-14T14:35:43.292Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:36:12.998Z", "level":"error", "message":"pro is not defined", "stack":""}
{"timestamp":"2018-10-14T14:36:25.854Z", "level":"error", "message":"missing ) after argument list", "stack":""}
{"timestamp":"2018-10-14T14:36:29.489Z", "level":"error", "message":"missing ) after argument list", "stack":""}
{"timestamp":"2018-10-14T14:38:08.078Z", "level":"error", "message":"ReferenceError: winston is not defined", "stack":""}
{"timestamp":"2018-10-14T14:38:14.546Z", "level":"error", "message":"ReferenceError: winston is not defined", "stack":""}
{"timestamp":"2018-10-14T14:38:34.301Z", "level":"error", "message":"missing path", "stack":""}
{"timestamp":"2018-10-14T14:38:36.641Z", "level":"error", "message":"missing path", "stack":""}
{"timestamp":"2018-10-14T14:40:53.272Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:40:53.274Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:41:54.622Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:41:54.625Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:42:15.096Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:42:15.100Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:42:22.533Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:42:22.535Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-14T14:42:40.752Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-14T14:42:40.754Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-17T08:36:24.783Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:36:24.792Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:37:25.504Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:37:25.509Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:37:56.387Z", "level":"error", "message":"ReferenceError: networkId is not defined", "stack":""}
{"timestamp":"2018-10-17T08:38:44.426Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:38:44.431Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:39:01.348Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:39:01.352Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:39:21.036Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:24.925Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:26.194Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:29.573Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:33.826Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:40.759Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:43.395Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:39:56.028Z", "level":"error", "message":"missing ) after argument list", "stack":""}
{"timestamp":"2018-10-17T08:40:03.136Z", "level":"error", "message":"await is only valid in async function", "stack":""}
{"timestamp":"2018-10-17T08:40:30.930Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:40:30.935Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:40:38.735Z", "level":"error", "message":"Invalid or unexpected token", "stack":""}
{"timestamp":"2018-10-17T08:40:49.325Z", "level":"error", "message":"ReferenceError: owner is not defined", "stack":""}
{"timestamp":"2018-10-17T08:40:59.278Z", "level":"error", "message":"Unexpected token }", "stack":""}
{"timestamp":"2018-10-17T08:41:03.407Z", "level":"error", "message":"Unexpected token }", "stack":""}
{"timestamp":"2018-10-17T08:41:31.466Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:41:31.472Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:41:31.473Z", "level":"error", "message":"Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:41:56.247Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:41:56.252Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:41:56.254Z", "level":"error", "message":"Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:42:52.359Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:42:52.362Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:42:52.363Z", "level":"error", "message":"Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:43:00.403Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:43:00.404Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-17T08:43:32.006Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:43:32.011Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:44:39.733Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:44:39.737Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:47:52.189Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:47:52.194Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:48:16.592Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:48:16.600Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:51:05.610Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:51:05.614Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:51:31.139Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:51:31.142Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:54:28.887Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T08:54:28.892Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T08:56:30.947Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T10:46:38.218Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-17T10:46:38.220Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-17T10:47:04.247Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-17T10:57:26.082Z", "level":"error", "message":"Error: Error: CONNECTION ERROR: Couldn't connect to node on WS.", "stack":""}
{"timestamp":"2018-10-18T10:10:28.331Z", "level":"error", "message":"MongoError: command find requires authentication", "stack":""}
{"timestamp":"2018-10-18T10:10:37.060Z", "level":"error", "message":"MongoError: command find requires authentication", "stack":""}
{"timestamp":"2018-10-18T10:10:43.311Z", "level":"error", "message":"MongoError: command find requires authentication", "stack":""}
{"timestamp":"2018-10-18T10:10:48.785Z", "level":"error", "message":"MongoError: command find requires authentication", "stack":""}
{"timestamp":"2018-10-18T10:10:52.771Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-18T10:10:52.772Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-18T10:11:03.905Z", "level":"error", "message":"undefined", "stack":""}
{"timestamp":"2018-10-18T10:11:03.907Z", "level":"error", "message":"Error: connection not open", "stack":""}
{"timestamp":"2018-10-18T10:13:44.270Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:13:45.592Z", "level":"error", "message":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]", "stack":""}
{"timestamp":"2018-10-18T10:14:08.593Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:14:44.631Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:14:49.302Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:14:52.841Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:15:02.765Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:16:25.001Z", "level":"error", "message":"Error: Returned values aren't valid, did it run Out of Gas?", "stack":""}
{"timestamp":"2018-10-18T10:17:16.433Z", "level":"error", "message":"missing path", "stack":""}
{"timestamp":"2018-10-18T10:17:17.815Z", "level":"error", "message":"missing path", "stack":""}
